### ISSUE TITLE
[1.7.10] Treealyzer fruit name issue

### ISSUE THREAD

**Issue by psxlover** [ForestryMC/Binnie#272]
When using tree from ExtraTrees in the treealyzer, a "for." is added to the start of fruit names:
![2017-08-16_15 51 21](https://user-images.githubusercontent.com/1429524/29364086-1201e7e4-829b-11e7-888c-ab04ab3fdeed.png)
![2017-08-16_15 51 26](https://user-images.githubusercontent.com/1429524/29364104-1aa846b8-829b-11e7-9efe-b2fd5abcc9fb.png)

**Comment by KorDum** [comment]
Thanks for report!

**Comment by mezz** [comment]
Opening since this probably still needs a fix in 1.7.10

**Comment by KorDum** [comment]
@mezz @Nedelosk 
I need help :(
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/extratrees/genetics/ExtraTreeFruitGene.java#L316
https://github.com/ForestryMC/Binnie/blob/master-MC1.7.10/src/main/java/binnie/extratrees/genetics/ExtraTreeFruitGene.java#L421
I don't know, why it's not work. Can you help me?

**Comment by mezz** [comment]
I looked into it and in 1.7.10, Forestry does this:
https://github.com/ForestryMC/ForestryMC/blob/mc-1.7.10/src/main/java/forestry/arboriculture/gui/GuiTreealyzer.java#L245

It expects `getDescription()` to be unlocalized, and it  adds `for.` to the front.

It would be a lot of work to fix this properly (it's already fixed in later Forestry) so I am just going to hack around it in Binnie's to fix it.

**Comment by mezz** [comment]
Fixed in 2.0.22
