### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by 3TUSK** [ForestryMC/Binnie#3]
Sorry for bothering i18n stuff during early development.
Questions to ask:
1. there is [an existed repository](https://github.com/binnie567/Binnies-Mods-Localisation) for i18n support of binnie. Will we have a separate repository like that?
2. will a pull request of i18n support be accept, if there is any? assuming there is no breaking change, I can open a pull request of i18n support (Simplified Chinese) right now, as I have already opened one last year. 
3. for last time I checked out binnie, there were still a lot of hard-coded stuff (e.g. name of butterflies, name of flowers, maybe text in all GUIs, cannot recall all of them). Can they be translatable by any chance?

**Comment by mezz** [comment]
I have seen a LOT of hard-coded localization so far. It will be a big task to fix.
First priority is getting this mod working, there is still a lot to do.
Getting this mod's localization to be as good as Forestry's is a goal, just not in the short-term.

I don't really like having separated projects for localization, I'm fine with giving you permission to work with this project because I trust you will not edit other things. Is there a big benefit to having the project separated? The Forestry localization gets forgotten sometimes, and changes do not show up in the changelog.

**Comment by 3TUSK** [comment]
Separating i18n project can makes things clear, as you will have separate lists of coders and translators... Said asie somewhere. IIRC he said so in an issue in CharsetMC/CharsetMC, but I cannot remember which one it is.

Anyhow, I will keep eye on that and won't open pull request until it is almost ready to go. I have already stuck on some flowers' name now...

**Comment by 3TUSK** [comment]
> ...and my phone tells me that this email was delivered 3 days after i wrote it. what the...
