### ISSUE TITLE
[1.12] Botany lacks oredicts

### ISSUE THREAD

**Issue by asiekierka** [ForestryMC/Binnie#303]
Pigmented Glass should be blockGlass, IMO. Not sure if Clay shouldn't also be oredicted...

**Comment by RusTit** [comment]
@mezz I looked at the code, it seems to be fixed?

**Comment by mezz** [comment]
I don't see "blockGlass" anywhere in the project, I don't think this has been fixed.

**Comment by RusTit** [comment]
Single mention
https://github.com/ForestryMC/Binnie/blob/66eabfc2bda7186e822c32bbc2dc73d4f4864df3/botany/src/main/resources/assets/botany/lang/en_US.lang#L39
so i think this is it
https://github.com/ForestryMC/Binnie/blob/66eabfc2bda7186e822c32bbc2dc73d4f4864df3/botany/src/main/java/binnie/botany/blocks/BlockStainedGlass.java#L141-L145
They are registered now without a Oredictionary
https://github.com/ForestryMC/Binnie/blob/66eabfc2bda7186e822c32bbc2dc73d4f4864df3/botany/src/main/java/binnie/botany/modules/ModuleCeramic.java#L54-L75
Therefore, it seemed to me that the problem was no longer relevant

**Comment by RusTit** [comment]
Ah, I misunderstood the problem.

**Comment by RusTit** [comment]
@mezz Where can I look at the keys for the Oredictionary ("blockGlass")? In the source code of forge?

**Comment by mezz** [comment]
You can find it in Forge here:
https://github.com/MinecraftForge/MinecraftForge/blob/a40df67004dc02c502f7b07d8fe7e6349273514c/src/main/java/net/minecraftforge/oredict/OreDictionary.java#L203-L205

Ore dictionary is just a loose agreement between mods, lots of them are not in Forge at all. For this though there is a pretty clear case for it in Forge.

**Comment by RusTit** [comment]
@mezz Probably you can close it too?
