### ISSUE TITLE
Continuous Power Usage from Machines

### ISSUE THREAD

**Issue by SnowShock35** [ForestryMC/Binnie#378]
Hi,

I have a feature suggestion/query for Binnie's Mods for Minecraft 1.12.2. 

All the machines in the mod appear to continue using energy when inactive. I was curious to know if this was intentional or just how it was from previous versions. I know that Forestry previously did the same some time ago, but this has since been changed (to my knowledge). Therefore, I feel that it is perhaps better to make similarities between the two mods since Binnie's Mods is an addon to Forestry and would cause less confusion.

**Comment by RusTit** [comment]
@mezz I did the test on the current version. No usage...
![2018-03-24_17 21 29](https://user-images.githubusercontent.com/29846693/37861556-d972bc7e-2f87-11e8-9fba-3815c15e3ae4.png)
![2018-03-24_17 21 31](https://user-images.githubusercontent.com/29846693/37861557-d9a05d00-2f87-11e8-8481-7ba7e37ded10.png)

**Comment by mezz** [comment]
Have you checked with RF as well?

**Comment by SnowShock35** [comment]
I can check, one moment.

**Comment by SnowShock35** [comment]
Okay, can confirm that all the genetic machines are no longer zapping RF constantly. Thanks, Mezz, you can go ahead and close this now.

**Comment by RusTit** [comment]
Do not hurry if you can check the other machines too.

**Comment by RusTit** [comment]
@mezz 
I also did tests with the RF energy.
The problem was not confirmed.
![2018-03-25_18 20 07](https://user-images.githubusercontent.com/29846693/37873131-525a4f18-3059-11e8-8308-60d80b1479e0.png)
![2018-03-25_18 20 11](https://user-images.githubusercontent.com/29846693/37873132-528967f8-3059-11e8-89eb-dc1a38870ac8.png)
![2018-03-25_18 20 13](https://user-images.githubusercontent.com/29846693/37873133-52c05bbe-3059-11e8-91d0-400259a732ba.png)

**Comment by mezz** [comment]
Thanks, looks good then.
