### ISSUE TITLE
[1.12.2] Botany Flower Spawning Issue

### ISSUE THREAD

**Issue by CakeFlour** [ForestryMC/Binnie#405]
While attempting to do the Botany Mod, I ran into a weird occurrence.
Placing down 2 or more flowers onto the Botany soil makes it start Generating a bunch of different higher tier flowers such as Cornflowers at random, with random colors as well. There doesn't seem to be any rhyme or reason to it at all. 
Also, placing a vanilla flower on soil I believe is supposed to convert it into a Binnie's version of it, but sometimes it does not work whatsoever. (Vanilla Flowers do not react at all.)
The rate of random flower production is high as well, I was able to fill up a standard double chest with flowers within a few in game days.
This has been tested on both a Server, and Single Player, with the same result. 
(Direwolf20 1.8.0 and FTB Revelations 1.5.0 have the same problem)

**Comment by lavaheart** [comment]
I've had same problem, wanted to breed Delphiniums so I put lilac and bluet next to each other. and a Dahlia, Aster and a goldenrod seedling spawned next to them within a minute both had inactive genes of a geranium or daffodil. This was my first time breeding flowers and I only had butterflies nearby no bees.

It makes it hard to breed specific colors for dye that's for sure.

**Comment by sealchan1** [comment]
As of today this is still an issue.  I am, for fun, attempting to understand the code so I can see what is amiss.

There appears to be mutations defined in FlowerDefiinition.java that are not being followed, at least in the case of the determination of what germlings might appear on a soil block.  

Can anyone confirm whether this mechanic is currently working as expected in the Multiblock Farm?  I notice that in https://www.youtube.com/watch?v=XiViG4PHUsI the breeding of flowers is shown in the Multiblock Farm but not in the soil part of the demo.  So perhaps soil breeding was added but not completely since that time such that it doesn't follow the expected mutation pathways.

**Comment by sealchan1** [comment]
Okay so I think I see where in Binnie's implementation of Flower mutations there is an "exchange" of genetic information but no effort to restrict the mutated species to the proper list of target species according to the mutation "ladder".  In binnie/botany/genetics/Flower.java's getMutation method there is no attempt to "getCombinations" which determines the list of viable species an "offspring" can potentially mutate to.  I determined this by comparing to forestry/apiculture/genetics/Bee.java where getMutation() calls getCombinations() to presumably apply this limitation.
