### ISSUE TITLE
No access to Refined Bee Line

### ISSUE THREAD

**Issue by BeesKneeesGeez** [ForestryMC/Binnie#513]
Although JEI lists the Oily, Distilled, and Refined bees, there seems to be no way to breed them. The master registry lists no possible mutation for Primeval and Modest, and does not include Oily and Refined in the database. Distilled is listed, but without any way to breed it.

Binnie's Mod 1.12.2-2.5.0.160
Minecraft 1.12.2
Forge 1.12.2-14.23.2.2654

**Comment by RusTit** [comment]
Availability of bees is configured in this section of the code.
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeeSpecies.java#L21-L51
Bee will be add to black list (no breeding recipe) if its product items or specialization (also items) do not exist in the current assembly of minecraft. Usually there is no mod that adds this item
For example **Distilled:** is not in black list but it depends on OIL
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeeDefinition.java#L759-L769
OIL bee is in black list because where is no oil fluid in your game.
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/genetics/ExtraBeeDefinition.java#L742-L755
Code: `.addSpecialty(EnumHoneyComb.OIL.get(1), 0.05f);` trying to register bee spec.
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/items/types/EnumHoneyComb.java#L48-L54
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/items/types/EnumPropolis.java#L15
https://github.com/ForestryMC/Binnie/blob/20f77a4dbbef6f4dec4a367800c898724a099390/extrabees/src/main/java/binnie/extrabees/items/types/EnumPropolis.java#L67-L70
In general, if you add a mod that will register the liquid "Oil", then the corresponding bee will become available.
Similar logic works for other bees without breeding.

**Comment by BeesKneeesGeez** [comment]
I understand now; I was confused because I have Thermal Foundation installed, which does technically include "oil". However TF's code for the oil doesn't use the same syntax as this mod, so it goes unrecognized.  Therefore the Bees are blacklisted and unavailable to breed.
