### ISSUE TITLE
[1.7.10]crash when have chromaticraft

### ISSUE THREAD

**Issue by KuroPeach** [ForestryMC/Binnie#518]
when i seach steel or charcoal,the game will crash,when i disable Extra Trees will nothing.
Forgive me my bad English

**Comment by KuroPeach** [comment]
crash report
[charcoal](https://paste.ubuntu.com/p/ZBwS37J9bV/)  
[steel](url)simple pack no steel..

**Comment by temp1011** [comment]
Relevant part of chromaticraft https://github.com/ReikaKalseki/ChromatiCraft/blob/56819445d4cad5880f7b37f08c39cdd63d53b452/TileEntity/Processing/TileEntityCrystalFurnace.java#L195-L202. Relevant part of Binnie https://github.com/ForestryMC/Binnie/blob/765dade9bd22885f208294e2eb348b7d9c43650f/src/main/java/binnie/extratrees/block/BlockETLog.java#L129-L131. Something calls getBlockName with ore dictionary wildcard it looks like. I don't know if this should be fixed by Binnie or Chromaticraft.

**Comment by mezz** [comment]
To stop this crash, we should use meta 0 when it's out of range.
I had an argument with Reika about this before with Forestry, they're badly misusing the ore dictionary and will not fix it.
https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/530

**Comment by temp1011** [comment]
For some reason the PR didn't auto close this but I believe that this is sorted now.

**Comment by mezz** [comment]
I think github will only auto-close from commits on the main branch. This was on 1.7.10 so it didn't do it.
