### ISSUE TITLE
Can't disable Compartment's via CT

### ISSUE THREAD

**Issue by StoneLegion** [ForestryMC/Binnie#576]
Some odd reason no matter what I do I can't seem to disable Compartment's via CT. 

Example:
```recipes.remove(<binniecore:storage:*>);
recipes.remove(<binniecore:storage>);
recipes.remove(<binniecore:storage:1>);
recipes.removeShaped(<binniecore:storage>);
recipes.removeShaped(<binniecore:storage:*>);
recipes.removeShaped(<binniecore:storage:1>);```

Either way nothing removes them I even tried labeling the file z just in case but nothing else is editing the binnie mods.

**Comment by StoneLegion** [comment]
I also tried this method:
```recipes.removeByRecipeName("binniecore:compartment");```

**Comment by StoneLegion** [comment]
```recipes.removeAll();```

So talking to the devs of CT they are saying the recipes are being registered too late. I mean I used the above and still the containers exist but I can't even create a bench anymore to give you an idea what it does. 

Either way thanks for your time.

**Comment by justinrusso** [comment]
This is indeed caused by the recipes being registered too late.
https://github.com/ForestryMC/Binnie/blob/4136ae8e6a166d7c9db4afed20a8225d9dfde297/core/src/main/java/binnie/core/machines/storage/ModuleStorage.java#L33

There is a recipe registration event that would probably be the most ideal. Quote source: https://mcforge.readthedocs.io/en/latest/concepts/registries/
```
RegistryEvents are currently supported for the following types: Block, Item, Potion, Biome, SoundEvent, PotionType, Enchantment, IRecipe, VillagerProfession, EntityEntry
```

CraftTweaker runs during that event on the lowest priority.
